version: '3.8'

services:
  web:
    build: .
    command: gunicorn --chdir django_blog django_blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/django_blog/static
      - media_volume:/app/django_blog/media
    expose:
      - 8000
    env_file:
      - django_blog/.env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=django_blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/django_blog/static
      - media_volume:/app/django_blog/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: