# Generated by Django 4.2.20 on 2025-04-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(max_length=300, verbose_name="Description of the category"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, verbose_name="Category URL"),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Category name "),
        ),
    ]
