# Generated by Django 4.2.20 on 2025-04-20 03:26

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_category_description_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=500, verbose_name="Краткое описание"),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=500, verbose_name="Полный текст записи"),
        ),
    ]
