{
 "title": "Django Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average Response Time by View",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_sum[5m]) / rate(django_http_requests_latency_seconds_by_view_method_count[5m])",
     "legendFormat": "{{method}} {{view}}"
    }
   ]
  },
  {
   "title": "HTTP Requests by Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_method_total[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Response Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(django_http_responses_total_by_status_total[5m])",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}