# Generated by Django 4.2.20 on 2025-04-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="code_created_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Время создания кода"),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verification_code",
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name="Код подтверждения email"),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="Email подтвержден"),
        ),
    ]
